### ISSUE TITLE
can't get emoji from url

### ISSUE THREAD

**Issue by huancnttuet** [cagpie/node-canvas-with-twemoji#11]
I think you should set a try catch and reject function as follows:  

![image](https://user-images.githubusercontent.com/43350974/144037857-05819245-34bf-4dbf-b0f3-759d0d0c400f.png)

I got an error like this when an emoji failed to load 
`UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory ''`

**Comment by cagpie** [comment]
The problem is where to handle the exception when the image load fails.
Perhaps even if you add try-catch and resolve-reject like this code, you will get the same error unless you finally handle the reject.

Ideally, the developer using the module should handle the exception,
Few developers can predict that an exception will occur when loading an emoji image.

Therefore, if the emoji reading fails, `console.error` is output and the process is changed to avoid interruption. (no reject)

```javascript
    try {
      const image = await loadImage(url);
      cachedTwemojiImages.set(url, image);

      res(image);
    } catch (e) {
      console.error(e)
    }
```
